---

- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:

  - name: Install a list of packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - nmap
        - iperf
