---

- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:

  - lineinfile:
      dest: /etc/apt/sources.list
      state: absent
      regexp: 'cdrom'

  - name: Install a list of dependencies
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - nmap
        - curl
        - iperf
        - cmake
        - make
        - gcc
        - g++
        - flex
        - bison
        - libpcap-dev
        - libssl-dev
        - python-dev
        - swig
        - zlib1g-dev
        - libgeoip-dev
        - net-tools
        - lsof
        - apt-transport-https
        - openjdk-11-jdk
        - gnupg1
        - sudo
