---
# Main playbook installing the Suricata and Zeek tools
- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:

  - name: Check if running Kali
    shell: grep "kali /etc/issue" && echo "kali"
    register: kali
    ignore_errors: yes
    tags:
      - testing

  - name: Exit if running Kali
    fail: msg="Playbook not intended for Kali Linux, try Debian or Ubuntu"
    when: kali.stdout == "kali"
    tags:
      - testing

  - name: Install a list of main packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - tcpdump
        - wireshark
        - bro
        - broctl
        - bro-aux
        - suricata
        - suricata-oinkmaster
