---
# Main playbook installing the Suricata and Zeek tools
- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:

  - name: Exit if running Kali
    fail: msg="Playbook not intended for Kali Linux, try Debian or Ubuntu"
    when: ansible_facts['distribution'] == "Kali GNU/Linux"
    tags:
      - testing

  - name: Install OBS key for Zeek install
    shell: wget -qO - https://download.opensuse.org/repositories/security:zeek/Debian_11/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/security_zeek.gpg

  - name: Add OBS repository for Zeek
    copy:
      content="deb http://download.opensuse.org/repositories/security:/zeek/Debian_11/ /"
      dest="/etc/apt/sources.list.d/security:zeek.list"

  - name: Install a list of main packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - tcpdump
        - wireshark
        - zeek
        - suricata
        - suricata-oinkmaster
