---
# Main playbook installing the Suricata and Zeek tools
- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
  - name: Install Elastic stack key
    shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

  - name: Install a list of dependencies
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - apt-transport-https

  - name: Add elastic repository
    copy:
      content="deb https://artifacts.elastic.co/packages/7.x/apt stable main"
      dest="/etc/apt/sources.list.d/elastic-7.x.list"

  # Run the equivalent of "apt-get update" as a separate step
  - apt: update_cache=yes
    tags:
      - packages

  - name: Create the file /etc/default/logstash, if it doesnt exist already
    file:
      path: /etc/default/logstash
      state: touch


  - name: Install Elasticsearch etc.
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - unzip
        - elasticsearch
        - logstash
        - redis-server
        - nginx
        - apache2-utils
        - kibana
        - filebeat



  - name: copy logstash config
    action:
      copy src=files/logstash-suricata.conf
      dest=/etc/logstash/conf.d/suricata.conf owner=root group=root mode=0644

  - name: copy Zeek filebeat config
    action:
      copy src=files/filebeat-zeek.conf
      dest=/etc/filebeat/modules.d/zeek.yml owner=root group=root mode=0644

  - name: Enable Zeek in Filebeat
    shell: filebeat modules enable zeek

  - name: Restart service filebeat, in all cases
    service:
      name: filebeat
      state: restarted

  - name: Ensure Zeek logs in JSON format
    lineinfile:
      path: /etc/bro/site/local.bro
      regexp: 'json-logs'
      line: @load policy/tuning/json-logs.zeek

  - name: Restart service Zeek (bro), in all cases
    service:
      name: bro
      state: restarted

  - name: Fix permissions on eve.log so logstash can read
    file: path=/var/log/suricata/eve.json mode=0775

# start services
  - service: name=elasticsearch state=started enabled=yes
  - service: name=filebeat state=started enabled=yes
  - service: name=logstash state=started enabled=yes
  - service: name=nginx state=started enabled=yes
  - service: name=suricata state=started enabled=yes
  - service: name=kibana state=started enabled=yes
