---
- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
  - name: Remove CDROM from sources
    lineinfile:
      dest: /etc/apt/sources.list
      state: absent
      regexp: 'cdrom'

  - name: Install a list of dependencies for Atom editor etc.
    package:
      name:
        - curl
        - iperf
        - net-tools
        - apt-transport-https

  - name: Add an Apt signing key, for Atom editor
    apt_key:
      url: https://packagecloud.io/AtomEditor/atom/gpgkey
      state: present

  - name: Add Atom repository
    apt_repository:
      repo: deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main
      state: present
      filename: atomeditor.list

  - name: Install Atom editor etc.
    apt:
      name: atom
