---
# Main playbook installing the Suricata and Zeek tools
- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
  - name: Install a list of main packages for LaTeX
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - latexmk
