---
# Main playbook installing the Suricata and Zeek tools
- name: run the playbook tasks on the localhost
  hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: Install a list of main packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - vlan
        - tcpdump
        - wireshark
        - bro
        - broctl
        - bro-aux
        - isc-dhcp-server
        - unbound



  # Set ip forwarding on in /proc and verify token value with the sysctl command
  - sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes

  # Set ip forwarding on in /proc and in the sysctl file and reload if necessary
  - sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
